import { useState } from 'react'
import { blocks, checkpoints, csfs, getBlockPlan, getWeekPlan, kgi, materials, missCodes, procedures, roadmapVersion, weekdayPlans } from './data/roadmap'
import { addDays, blockForWeek, canRecordToday, dateKey, datesForWeek, daysBetween, distinctTrendWeeks, formatJapaneseDate, nextCheckpoint, weekPosition, weekdayFor } from './lib/date'
import { aggregateWeek, dailyLogLine, percent, topMissCode, trendTableMarkdown } from './lib/metrics'
import { emptyData, loadData, makeId, parseImport, saveData, serializeData, type AppData, type Mode, type StudyLog, type WeeklyMeasure } from './lib/storage'

type Tab = 'today' | 'records' | 'roadmap'
const shortMenu = ['3分 retrieval', '4分問題', '2分答え合わせ', '1分error log']
const tiredMenu = ['昨日の単語', '昨日の音声', '昨日の誤答']

function plannedForDay(key: string): number { return weekdayPlans.find((item) => item.day === weekdayFor(key))?.minutes ?? 10 }
function modeActual(mode: Mode, planned: number): number { return mode === 'short' || mode === 'tired' ? 10 : planned } // 提案(PDF外): 疲れた日は10分を記録の初期値とする

function App() {
  const [data, setData] = useState<AppData>(() => loadData())
  const [tab, setTab] = useState<Tab>('today')
  const [showSettings, setShowSettings] = useState(false)
  const [selectedWeek, setSelectedWeek] = useState<number | null>(null)
  const [gptPreview, setGptPreview] = useState('')
  const [replyDraft, setReplyDraft] = useState('')
  const [exchangeId, setExchangeId] = useState<string | null>(null)
  const today = dateKey()
  const position = weekPosition(data.settings.startDate, today)
  const activeWeek = position.week
  const viewWeek = selectedWeek ?? activeWeek
  const viewDates = datesForWeek(data.settings.startDate, viewWeek)

  const persist = (next: AppData) => { setData(next); saveData(next) }
  const patchData = (change: (current: AppData) => AppData) => persist(change(data))
  const logFor = (key: string, week = viewWeek): StudyLog => {
    const saved = data.logs[key]
    if (saved) return saved
    return { date: key, week, weekday: weekdayFor(key), plannedMinutes: plannedForDay(key), roadmapVersion, mode: 'normal', actualMinutes: plannedForDay(key), done: false }
  }
  const todayLog = logFor(today, activeWeek)
  const updateLog = (key: string, change: Partial<StudyLog>) => {
    if (!canRecordToday(position.status)) return
    patchData((current) => ({ ...current, logs: { ...current.logs, [key]: { ...logFor(key, weekPosition(current.settings.startDate, key).week), ...change } } }))
  }
  const weekLogs = viewDates.map((key) => logFor(key, viewWeek))
  const summary = aggregateWeek(weekLogs)
  const currentBlock = getBlockPlan(blockForWeek(viewWeek))
  const checkpoint = nextCheckpoint(viewWeek)
  const target = checkpoints.find((item) => item.week === checkpoint)!

  const setMode = (mode: Mode) => { if (canRecordToday(position.status)) updateLog(today, { mode, actualMinutes: modeActual(mode, todayLog.plannedMinutes) }) }
  const changeMinutes = (amount: number) => { if (canRecordToday(position.status)) updateLog(today, { actualMinutes: Math.max(0, Math.min(300, todayLog.actualMinutes + amount)) }) }
  const toggleDone = () => { if (canRecordToday(position.status)) updateLog(today, { done: !todayLog.done, actualMinutes: todayLog.actualMinutes || todayLog.plannedMinutes }) }

  const generateConsultation = () => {
    const measure = data.weeklyMeasures[String(viewWeek)]
    const lastFour = distinctTrendWeeks(viewWeek).map((week) => {
      const logs = datesForWeek(data.settings.startDate, week).map((key) => logFor(key, week))
      const result = aggregateWeek(logs)
      const weekMeasure = data.weeklyMeasures[String(week)]
      const p5 = percent(weekMeasure?.p5)
      const p7 = percent(weekMeasure?.p7)
      return `| ${week} | ${result.actualMinutes}/${result.plannedMinutes}分 | ${result.doneDays}/6 | ${result.rate}% | ${topMissCode(weekMeasure)} | ${p5 === undefined ? '—' : `${p5}%`} | ${p7 === undefined ? '—' : `${p7}%`} |`
    })
    const daily = viewDates.map((key) => dailyLogLine(key, weekdayFor(key), data.logs[key], plannedForDay(key))).join('\n')
    const rates = measure ? `P2 ${percent(measure.p2) ?? '—'}% / P3・4 ${percent(measure.p34) ?? '—'}% / P5 ${percent(measure.p5) ?? '—'}% / P7 ${percent(measure.p7) ?? '—'}% / 7日後単語 ${percent(measure.vocabulary7d) ?? '—'}%` : '未入力'
    const markdown = `# 英語ロードマップ相談\n\n## 現在地\n- Week ${viewWeek}/78\n- ブロック${currentBlock.block} ${currentBlock.name}\n- 重点: ${getWeekPlan(viewWeek).focus}\n- 成果物・KPI: ${getWeekPlan(viewWeek).deliverable}\n\n## 今週の計画と実績\n- ${summary.actualMinutes}/${summary.plannedMinutes}分（計画量達成率 ${summary.rate}%）\n- 実施日 ${summary.doneDays}/6\n\n## 日別ログ\n${daily}\n\n## 週次測定\n${rates}\n- 新規語数: ${measure?.newWords ?? '—'}\n- 同じ原因の再発率: ${measure?.recurrenceRate ?? '—'}%\n\n## ミスコード\n${Object.entries(measure?.missCounts ?? {}).map(([code, count]) => `${code}=${count}`).join(', ') || '未入力'}\n\n## KPI（次のCheckpoint Week ${checkpoint}）\n- 学習時間 ${summary.actualMinutes}/${target.studyMinutes}\n- 実施日 ${summary.doneDays}/${target.studyDays}\n- 7日後単語 ${measure ? percent(measure.vocabulary7d) ?? '—' : '—'}% / 目標 ${target.vocabulary7d}\n- P2 ${measure ? percent(measure.p2) ?? '—' : '—'}% / 目標 ${target.part2}\n- P3/4 ${measure ? percent(measure.p34) ?? '—' : '—'}% / 目標 ${target.part34}\n- P5 ${measure ? percent(measure.p5) ?? '—' : '—'}% / 目標 ${target.part5}\n- P7 ${measure ? percent(measure.p7) ?? '—' : '—'}% / 目標 ${target.part7}\n- 再発率 ${measure?.recurrenceRate ?? '—'}% / 目標 ${target.recurrence}\n\n## 直近4週トレンド\n${trendTableMarkdown(lastFour)}\n\n## 測定・本人メモ\n${measure?.memo || '未入力'}\n\n## テスト記録\n${data.assessments.map((item) => `- ${item.name} / ${item.date} / L${item.listening ?? '—'} R${item.reading ?? '—'} Total${item.total ?? '—'}`).join('\n') || '未入力'}\n\nこのPDFロードマップ（78週・週100分）を前提に、来週の学習計画を調整してください。KGI（Week 78 過去テストBで700+）とPDFのルールは変更せず、必要なら配分のみ調整してください。回答の最後に『来週の変更：』として3行以内でまとめてください。`
    const consultationMarkdown = markdown
    const exchange = { id: makeId(), week: viewWeek, createdAt: new Date().toISOString(), prompt: consultationMarkdown }
    patchData((current) => ({ ...current, gptExchanges: [...current.gptExchanges, exchange] }))
    setExchangeId(exchange.id); setGptPreview(consultationMarkdown); setReplyDraft('')
  }

  const updateMeasure = (change: Partial<WeeklyMeasure>) => patchData((current) => ({ ...current, weeklyMeasures: { ...current.weeklyMeasures, [String(viewWeek)]: { ...(current.weeklyMeasures[String(viewWeek)] ?? {}), ...change } } }))
  const measure = data.weeklyMeasures[String(viewWeek)] ?? {}
  const updatePair = (field: 'p2' | 'p34' | 'p5' | 'p7' | 'vocabulary7d', key: 'correct' | 'total', value: number) => updateMeasure({ [field]: { ...(measure[field] ?? { correct: 0, total: 0 }), [key]: Math.max(0, value) } })
  const changeMiss = (code: string, amount: number) => updateMeasure({ missCounts: { ...(measure.missCounts ?? {}), [code]: Math.max(0, (measure.missCounts?.[code] ?? 0) + amount) } })

  const copyText = async (value: string) => {
    try { await navigator.clipboard.writeText(value) } catch { const area = document.createElement('textarea'); area.value = value; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove() }
  }
  const saveReply = () => {
    if (!replyDraft.trim() || !exchangeId) return
    patchData((current) => ({ ...current, reviews: { ...current.reviews, [String(viewWeek)]: [...(current.reviews[String(viewWeek)] ?? []), replyDraft.trim()] }, gptExchanges: current.gptExchanges.map((item) => item.id === exchangeId ? { ...item, reply: replyDraft.trim() } : item) }))
    setReplyDraft('')
  }

  const content = showSettings ? <Settings data={data} persist={persist} /> : tab === 'today' ? <TodayScreen {...{ data, position, today, todayLog, currentBlock, checkpoint, summary, viewWeek, setMode, changeMinutes, toggleDone, updateLog, setTab, setSelectedWeek }} /> : tab === 'records' ? <RecordsScreen {...{ data, viewWeek, viewDates, summary, target, measure, updateMeasure, updatePair, changeMiss, setSelectedWeek, generateConsultation, gptPreview, copyText, replyDraft, setReplyDraft, saveReply, setTab, onAddAssessment: (item) => patchData((current) => ({ ...current, assessments: [...current.assessments, item] })) }} /> : <RoadmapScreen activeWeek={activeWeek} />

  return <div className="app-shell">
    <header className="app-header"><div><p className="eyebrow">TOEIC 400 → 700</p><h1>英語ロードマップ</h1></div><button className="icon-button" aria-label="設定" onClick={() => setShowSettings((value) => !value)}>⚙</button></header>
    <main>{content}</main>
    {!showSettings && <nav className="tab-bar"><button className={tab === 'today' ? 'active' : ''} onClick={() => setTab('today')}>今日</button><button className={tab === 'records' ? 'active' : ''} onClick={() => setTab('records')}>週・記録</button><button className={tab === 'roadmap' ? 'active' : ''} onClick={() => setTab('roadmap')}>ロードマップ</button></nav>}
  </div>
}

function TodayScreen(props: { data: AppData; position: ReturnType<typeof weekPosition>; today: string; todayLog: StudyLog; currentBlock: ReturnType<typeof getBlockPlan>; checkpoint: number; summary: ReturnType<typeof aggregateWeek>; viewWeek: number; setMode: (mode: Mode) => void; changeMinutes: (amount: number) => void; toggleDone: () => void; updateLog: (key: string, change: Partial<StudyLog>) => void; setTab: (tab: Tab) => void; setSelectedWeek: (week: number) => void }) {
  const { data, position, today, todayLog, currentBlock, checkpoint, summary, setMode, changeMinutes, toggleDone, updateLog, setTab, setSelectedWeek } = props
  const canRecord = canRecordToday(position.status)
  const plan = getWeekPlan(position.week)
  const block = getBlockPlan(position.week > 0 ? position.week > 78 ? 6 : blockForWeek(position.week) : 1)
  const todayPlan = weekdayPlans.find((item) => item.day === weekdayFor(today)) ?? weekdayPlans[0]
  return <div className="stack">
    <section className="hero-card"><div className="hero-orbit">{position.status === 'before' ? '準備中' : position.status === 'after' ? '完走' : `Week ${position.week}/78`}</div><h2>{position.status === 'before' ? `開始まであと${position.daysUntilStart}日` : position.status === 'after' ? '78週間を完了しました' : `ブロック${block.block}・${block.name}`}</h2><p>{position.status === 'before' ? 'Week 1を先に確認して、開始日に備えましょう。' : position.status === 'after' ? '過去テストBの結果を記録して振り返りましょう。' : `次のCheckpoint（Week ${checkpoint}）まであと${Math.max(0, checkpoint - position.week)}週`}</p></section>
    <section className="card"><div className="section-heading"><h2>今週の進み具合</h2><span>{summary.actualMinutes}/{summary.plannedMinutes}分</span></div><div className="progress"><span style={{ width: `${Math.min(100, summary.actualMinutes)}%` }} /></div><div className="stat-row"><span>計画量達成率 <strong>{summary.rate}%</strong></span><span>実施日 <strong>{summary.doneDays}/6</strong></span></div></section>
    <section className="card"><p className="eyebrow">今週の重点</p><h2>{plan.focus}</h2><p className="muted">成果物・KPI：{plan.deliverable}</p></section>
    <section className="card today-card"><div className="section-heading"><div><p className="eyebrow">今日のメニュー・{todayPlan.minutes}分</p><h2>{todayPlan.title}</h2></div><span className={todayLog.done ? 'pill done' : 'pill'}>{todayLog.done ? '完了' : '未完了'}</span></div><div className="mode-switch"><button disabled={!canRecord} className={todayLog.mode === 'normal' ? 'selected' : ''} onClick={() => setMode('normal')}>通常</button><button disabled={!canRecord} className={todayLog.mode === 'short' ? 'selected' : ''} onClick={() => setMode('short')}>時間がない（10分）</button><button disabled={!canRecord} className={todayLog.mode === 'tired' ? 'selected' : ''} onClick={() => setMode('tired')}>疲れた日</button></div>{todayLog.mode !== 'normal' && <div className="mode-note"><strong>{todayLog.mode === 'short' ? '10分の基本形' : '新規学習を捨てる日'}</strong><ul>{(todayLog.mode === 'short' ? shortMenu : tiredMenu).map((item) => <li key={item}>{item}</li>)}</ul></div>}<div className="minute-row"><button disabled={!canRecord} onClick={() => changeMinutes(-5)} aria-label="5分減らす">−5</button><strong>{todayLog.actualMinutes}分</strong><button disabled={!canRecord} onClick={() => changeMinutes(5)} aria-label="5分増やす">＋5</button><small>予定 {todayLog.plannedMinutes}分</small></div><button disabled={!canRecord} className={`primary-button ${todayLog.done ? 'secondary' : ''}`} onClick={toggleDone}>{todayLog.done ? '完了を取り消す' : '完了にする'}</button><details><summary>メモ（任意）</summary><textarea disabled={!canRecord} defaultValue={todayLog.memo ?? ''} onBlur={(event) => updateLog(today, { memo: event.target.value })} placeholder="今日の気づき" /></details></section>
    <section className="card compact-links"><button onClick={() => { setTab('records'); setSelectedWeek(position.week) }}>週次測定を入力する</button><details><summary>10分基本形</summary><ol>{procedures.basic.map((item) => <li key={item}>{item}</li>)}</ol></details><details><summary>Listening 10分の手順</summary><ol>{procedures.listening.map((item) => <li key={item}>{item}</li>)}</ol></details><details><summary>現在の速度ルール</summary>{procedures.speed.map(([range, rule]) => <p key={range}><strong>{range}</strong>：{rule}</p>)}</details></section>
    {position.status === 'before' && <section className="card"><p className="eyebrow">Week 1プレビュー</p><h2>{getWeekPlan(1).focus}</h2><p>{getWeekPlan(1).deliverable}</p></section>}
    <p className="footnote">正答率をスコア換算しない。</p>
  </div>
}

function RecordsScreen(props: { data: AppData; viewWeek: number; viewDates: string[]; summary: ReturnType<typeof aggregateWeek>; target: typeof checkpoints[number]; measure: WeeklyMeasure; updateMeasure: (change: Partial<WeeklyMeasure>) => void; updatePair: (field: 'p2' | 'p34' | 'p5' | 'p7' | 'vocabulary7d', key: 'correct' | 'total', value: number) => void; changeMiss: (code: string, amount: number) => void; setSelectedWeek: (week: number) => void; generateConsultation: () => void; gptPreview: string; copyText: (value: string) => Promise<void>; replyDraft: string; setReplyDraft: (value: string) => void; saveReply: () => void; setTab: (tab: Tab) => void; onAddAssessment: (item: { id: string; name: string; date: string; listening?: number; reading?: number; total?: number }) => void }) {
  const { data, viewWeek, viewDates, summary, target, measure, updateMeasure, updatePair, changeMiss, setSelectedWeek, generateConsultation, gptPreview, copyText, replyDraft, setReplyDraft, saveReply } = props
  const days = viewDates.map((key) => ({ key, log: data.logs[key] }))
  const lastWeeks = Array.from({ length: 78 }, (_, index) => index + 1).reverse()
  return <div className="stack"><div className="week-selector"><button onClick={() => setSelectedWeek(Math.max(1, viewWeek - 1))}>‹</button><strong>Week {viewWeek}/78</strong><button onClick={() => setSelectedWeek(Math.min(78, viewWeek + 1))}>›</button></div><section className="card"><div className="section-heading"><h2>Week {viewWeek}の集計</h2><span>{summary.actualMinutes}/{summary.plannedMinutes}分</span></div><div className="progress"><span style={{ width: `${Math.min(100, summary.actualMinutes)}%` }} /></div><div className="stat-row"><span>実施日 <strong>{summary.doneDays}/6</strong></span><span>計画量達成率 <strong>{summary.rate}%</strong></span></div><div className="day-list">{days.map(({ key, log }) => <div className="day-row" key={key}><span><strong>{weekdayFor(key)}</strong> {key}</span><span>{log?.done ? `完了 ${log.actualMinutes}分` : '未完了'}</span></div>)}</div></section>
    <section className="card"><div className="section-heading"><h2>週次測定（任意）</h2><span>Week {viewWeek}</span></div><p className="muted">正答率は学習管理用の内部KPIで、スコア換算しません。</p><div className="measure-grid"><Pair label="P2" value={measure.p2} onChange={(key, value) => updatePair('p2', key, value)} /><Pair label="P3・4" value={measure.p34} onChange={(key, value) => updatePair('p34', key, value)} /><Pair label="P5" value={measure.p5} onChange={(key, value) => updatePair('p5', key, value)} /><Pair label="P7" value={measure.p7} onChange={(key, value) => updatePair('p7', key, value)} /><Pair label="7日後単語" value={measure.vocabulary7d} onChange={(key, value) => updatePair('vocabulary7d', key, value)} /></div><label>新規語数<input type="number" min="0" value={measure.newWords ?? ''} onChange={(event) => updateMeasure({ newWords: Number(event.target.value) })} /></label><p className="label-text">ミスコード（タップで＋1、−で減少）</p><div className="miss-grid">{missCodes.map(([code, label]) => <div className="miss-chip" key={code}><span title={label}>{code}</span><button onClick={() => changeMiss(code, -1)}>−</button><strong>{measure.missCounts?.[code] ?? 0}</strong><button onClick={() => changeMiss(code, 1)}>＋</button></div>)}</div><label>同じ原因の再発率（%）<input type="number" min="0" max="100" value={measure.recurrenceRate ?? ''} onChange={(event) => updateMeasure({ recurrenceRate: Number(event.target.value) })} /></label><label>次週変更メモ<textarea value={measure.nextMemo ?? ''} onChange={(event) => updateMeasure({ nextMemo: event.target.value })} /></label><label>本人メモ<textarea value={measure.memo ?? ''} onChange={(event) => updateMeasure({ memo: event.target.value })} /></label></section>
    <section className="card"><div className="section-heading"><h2>KPIパネル</h2><span>次のCheckpoint W{target.week}</span></div><div className="kpi-note"><span>先行指標：時間・実施日・新規語</span><span>遅行指標：再生率・Part%・再発率・テスト</span></div><KpiRow label="学習時間" value={`${summary.actualMinutes}分`} target={target.studyMinutes} ok={summary.actualMinutes >= 100} /><KpiRow label="実施日" value={`${summary.doneDays}日`} target={target.studyDays} ok={summary.doneDays >= 6} /><KpiRow label="新規語" value={measure.newWords === undefined ? '—' : `${measure.newWords}語`} target="記録" /><KpiRow label="7日後単語" value={measure.vocabulary7d ? `${percent(measure.vocabulary7d)}%` : '—'} target={target.vocabulary7d} /><KpiRow label="P2 / P3・4 / P5 / P7" value={[measure.p2, measure.p34, measure.p5, measure.p7].map((item) => item ? `${percent(item)}%` : '—').join(' / ')} target={`${target.part2} / ${target.part34} / ${target.part5} / ${target.part7}`} /><KpiRow label="同じ原因の再発率" value={measure.recurrenceRate === undefined ? '—' : `${measure.recurrenceRate}%`} target={target.recurrence} /><p className="footnote">Fresh Test B：{target.freshTestB}。正答率をスコア換算しない。</p></section>
    <section className="card"><h2>過去週</h2><div className="past-list">{lastWeeks.map((week) => { const weekKeys = datesForWeek(data.settings.startDate, week); const logs = weekKeys.map((key) => data.logs[key]).filter(Boolean) as StudyLog[]; const result = aggregateWeek(logs.length ? logs : weekKeys.map((key) => ({ ...data.logs[key], date: key, week, weekday: weekdayFor(key), plannedMinutes: plannedForDay(key), roadmapVersion, mode: data.logs[key]?.mode ?? 'normal', actualMinutes: data.logs[key]?.actualMinutes ?? 0, done: data.logs[key]?.done ?? false }))); return <button className={`past-row ${week === viewWeek ? 'current' : ''}`} key={week} onClick={() => setSelectedWeek(week)}><span>W{week}</span><div className="mini-bar"><i style={{ width: `${Math.min(100, result.actualMinutes)}%` }} /></div><span>{result.actualMinutes}分・{result.doneDays}日</span><span>{topMissCode(data.weeklyMeasures[String(week)])}</span></button> })}</div></section>
    <section className="card"><div className="section-heading"><h2>GPTに相談</h2><button className="small-button" onClick={generateConsultation}>Markdown生成</button></div>{gptPreview && <><textarea className="preview" value={gptPreview} readOnly /><button className="secondary-button" onClick={() => copyText(gptPreview)}>コピー</button><label>GPTの回答を保存<textarea value={replyDraft} onChange={(event) => setReplyDraft(event.target.value)} placeholder="貼り付けて保存" /></label><button className="primary-button" onClick={saveReply}>この週のメモとして保存</button></>}{data.reviews[String(viewWeek)]?.map((reply, index) => <details key={`${reply}-${index}`}><summary>保存した回答 {index + 1}</summary><p className="saved-reply">{reply}</p></details>)}</section>
    <section className="card"><h2>テスト記録</h2><AssessmentForm data={data} onSave={props.onAddAssessment} /></section>
  </div>
}

function Pair({ label, value, onChange }: { label: string; value?: { correct: number; total: number }; onChange: (key: 'correct' | 'total', value: number) => void }) { return <div className="pair"><strong>{label}</strong><label>正解<input type="number" min="0" value={value?.correct ?? ''} onChange={(event) => onChange('correct', Number(event.target.value))} /></label><label>全体<input type="number" min="0" value={value?.total ?? ''} onChange={(event) => onChange('total', Number(event.target.value))} /></label><span>{value ? `${percent(value) ?? 0}%` : '—'}</span></div> }
function KpiRow({ label, value, target, ok }: { label: string; value: string; target: string; ok?: boolean }) { return <div className="kpi-row"><span>{ok === undefined ? '○' : ok ? '✓' : '△'}</span><strong>{label}</strong><em>{value}</em><small>目標 {target}</small></div> }
function AssessmentForm({ data, onSave }: { data: AppData; onSave: (item: { id: string; name: string; date: string; listening?: number; reading?: number; total?: number }) => void }) { const [form, setForm] = useState({ name: '過去テストA', date: dateKey(), listening: '', reading: '', total: '' }); const save = () => { onSave({ id: makeId(), name: form.name, date: form.date, listening: Number(form.listening) || undefined, reading: Number(form.reading) || undefined, total: Number(form.total) || undefined }); setForm({ ...form, listening: '', reading: '', total: '' }) }; return <><div className="assessment-form"><select value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}><option>過去テストA</option><option>IIBCサンプル</option><option>過去テストB</option></select><input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /><input inputMode="numeric" placeholder="L" value={form.listening} onChange={(event) => setForm({ ...form, listening: event.target.value })} /><input inputMode="numeric" placeholder="R" value={form.reading} onChange={(event) => setForm({ ...form, reading: event.target.value })} /><input inputMode="numeric" placeholder="Total" value={form.total} onChange={(event) => setForm({ ...form, total: event.target.value })} /><button className="small-button" onClick={save}>追加</button></div>{data.assessments.map((item) => <div className="assessment-row" key={item.id}><span>{item.name}</span><span>{item.date}</span><strong>L{item.listening ?? '—'} / R{item.reading ?? '—'} / T{item.total ?? '—'}</strong></div>)}</> }

function RoadmapScreen({ activeWeek }: { activeWeek: number }) { const [open, setOpen] = useState(blockForWeek(activeWeek)); return <div className="stack"><section className="card intro-card"><p className="eyebrow">78週間の具体的ロードマップ</p><h2>少ない教材を、短く解き、深く復習する</h2><p>{kgi}</p></section>{blocks.map((block) => <section className={`card block-card ${block.block === open ? 'open' : ''}`} key={block.block}><button className="block-toggle" onClick={() => setOpen(open === block.block ? 0 : block.block)}><span><b>ブロック{block.block}</b><strong>{block.name}</strong></span><span>W{block.weeks[0]}–{block.weeks[1]} {open === block.block ? '⌃' : '⌄'}</span></button>{open === block.block && <div className="block-detail"><div className="allocation">L {block.allocation.listening}% ・ R {block.allocation.reading}% ・ 語彙文法 {block.allocation.vocabularyGrammar}% ・ 分析 {block.allocation.analysis}%</div>{Array.from({ length: 13 }, (_, index) => block.weeks[0] + index).map((week) => { const plan = getWeekPlan(week); const checkpoint = checkpoints.find((item) => item.week === week); return <div className={`roadmap-week ${week === activeWeek ? 'current' : ''} ${week < activeWeek ? 'past' : ''}`} key={week}><div><b>W{week}</b><strong>{plan.focus}</strong></div><p>{plan.deliverable}</p>{checkpoint && <span className="checkpoint">Checkpoint</span>}</div> })}</div>}</section>)}<section className="card"><details><summary>KGI / CSF</summary><h3>KGI</h3><p>{kgi}</p><h3>CSF</h3>{csfs.map((item) => <p key={item}>・{item}</p>)}</details><details><summary>教材リスト</summary>{materials.map((item) => <p key={item}>・{item}</p>)}</details></section></div> }

function Settings({ data, persist }: { data: AppData; persist: (data: AppData) => void }) { const [importMessage, setImportMessage] = useState(''); const backupStale = !data.settings.lastBackupAt || daysBetween(data.settings.lastBackupAt.slice(0, 10), dateKey()) > 7; const exportData = () => { const next = { ...data, settings: { ...data.settings, lastBackupAt: new Date().toISOString() } }; persist(next); const blob = new Blob([serializeData(next)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `erm-backup-${dateKey()}.json`; link.click(); URL.revokeObjectURL(url) }; const importData = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { const imported = parseImport(String(reader.result)); if (!imported) { setImportMessage('形式が正しくありません。schemaVersion: 1 のJSONを選んでください。'); return } if (window.confirm('現在のデータをインポートした内容で上書きしますか？')) { persist(imported); setImportMessage('インポートしました。') } }; reader.readAsText(file) }; const clear = () => { if (window.prompt('確認のため「削除」と入力してください') === '削除') { persist(emptyData()); setImportMessage('全データを削除しました。') } }; return <div className="stack"><section className="card"><div className="section-heading"><div><p className="eyebrow">設定</p><h2>開始日</h2></div><span>v1</span></div><input type="date" value={data.settings.startDate} onChange={(event) => persist({ ...data, settings: { ...data.settings, startDate: event.target.value } })} /><p className="muted">現在の開始日は {formatJapaneseDate(data.settings.startDate)} です。</p></section><section className="card"><h2>バックアップ</h2><p>最終バックアップ：{data.settings.lastBackupAt ? formatJapaneseDate(data.settings.lastBackupAt.slice(0, 10)) : '未実施'}</p>{backupStale && <p className="warning">7日以上バックアップがありません。iOS Safariはストレージを消去することがあるため、ホーム画面に追加して定期的に書き出してください。</p>}<div className="button-row"><button className="primary-button" onClick={exportData}>JSONを書き出す</button><label className="file-button">JSONを読み込む<input type="file" accept="application/json,.json" onChange={(event) => importData(event.target.files?.[0])} /></label></div>{importMessage && <p className="muted">{importMessage}</p>}</section><section className="card danger-card"><h2>全データ削除</h2><p>保存した学習記録、測定、相談メモを削除します。</p><button className="danger-button" onClick={clear}>削除</button></section><button className="secondary-button" onClick={() => window.location.reload()}>今日に戻る</button></div> }

export default App
